services:
  fastapi-backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.service
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
    command: gunicorn app:app
    develop:
      watch:
        - path: src/service/
          action: sync+restart
          target: /code/service/

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - /home/marcec/qdrant/data:/qdrant/storage