# syntax=docker/dockerfile:1

FROM python:3.11-slim

WORKDIR /code

COPY requirements.txt .

# Install required packages
#RUN apt-get update && \
#    apt-get install -y build-essential libssl-dev libffi-dev python3-dev libgl1 libglib2.0-0 libpoppler-dev libmagic-dev poppler-utils && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/*

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 7000

ENTRYPOINT ["gunicorn", "app:app"]
