# syntax=docker/dockerfile:1

FROM python:3.11-slim

WORKDIR /code

COPY requirements.txt .

RUN pip3 install -r requirements.txt

#COPY . .
COPY src/service/ ./service

EXPOSE 8000

#ENTRYPOINT ["gunicorn", "service.app:app"]
ENTRYPOINT ["gunicorn","-b", "0.0.0.0:8000", "service.app:app"]
